public class CalculatorJFrame extends javax.swing.JFrame {
     double num1,num2,res; 

    String operator,ans; 

    public CalculatorJFrame() { 

        initComponents(); 
}
 /** 

     * This method is called from within the constructor to initialize the form. 

     * WARNING: Do NOT modify this code. The content of this method is always 

     * regenerated by the Form Editor. 

     */ 

    @SuppressWarnings("unchecked") 

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents 

    private void initComponents() { 

 

        jTextFielddisplay = new javax.swing.JTextField(); 

        jButton1 = new javax.swing.JButton(); 

        jButton2 = new javax.swing.JButton(); 

        jButton3 = new javax.swing.JButton(); 

        jButton4 = new javax.swing.JButton(); 

        jButton5 = new javax.swing.JButton(); 

        jButton6 = new javax.swing.JButton(); 

        jButton7 = new javax.swing.JButton(); 

        jButton8 = new javax.swing.JButton(); 

        jButton9 = new javax.swing.JButton(); 

        jButton0 = new javax.swing.JButton(); 

        jButtonaclear = new javax.swing.JButton(); 

        jButtonequal = new javax.swing.JButton(); 

        jButtonplus = new javax.swing.JButton(); 

        jButtonminus = new javax.swing.JButton(); 

        jButtonmultiple = new javax.swing.JButton(); 

        jButtondivide = new javax.swing.JButton(); 

 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 

 

        jTextFielddisplay.setText(" "); 

 

        jButton1.setText("1"); 

        jButton1.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton1ActionPerformed(evt); 

            } 

        }); 

 

        jButton2.setText("2"); 

        jButton2.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton2ActionPerformed(evt); 

            } 

        }); 

 

        jButton3.setText("3"); 

        jButton3.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton3ActionPerformed(evt); 

            } 

        }); 

 

        jButton4.setText("4"); 

        jButton4.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton4ActionPerformed(evt); 

            } 

        }); 

 

        jButton5.setText("5"); 

        jButton5.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton5ActionPerformed(evt); 

            } 

        }); 

 

        jButton6.setText("6"); 

        jButton6.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton6ActionPerformed(evt); 

            } 

        }); 

 

        jButton7.setText("7"); 

        jButton7.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton7ActionPerformed(evt); 

            } 

        }); 

 

        jButton8.setText("8"); 

        jButton8.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton8ActionPerformed(evt); 

            } 

        }); 

 

        jButton9.setText("9"); 

        jButton9.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton9ActionPerformed(evt); 

            } 

        }); 

 

        jButton0.setText("0"); 

        jButton0.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButton0ActionPerformed(evt); 

            } 

        }); 

 

        jButtonaclear.setText("C"); 

        jButtonaclear.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtonaclearActionPerformed(evt); 

            } 

        }); 

 

        jButtonequal.setText("="); 

        jButtonequal.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtonequalActionPerformed(evt); 

            } 

        }); 

 

        jButtonplus.setText("+"); 

        jButtonplus.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtonplusActionPerformed(evt); 

            } 

        }); 

 

        jButtonminus.setText("-"); 

        jButtonminus.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtonminusActionPerformed(evt); 

            } 

        }); 

 

        jButtonmultiple.setText("*"); 

        jButtonmultiple.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtonmultipleActionPerformed(evt); 

            } 

        }); 

 

        jButtondivide.setText("/"); 

        jButtondivide.addActionListener(new java.awt.event.ActionListener() { 

            public void actionPerformed(java.awt.event.ActionEvent evt) { 

                jButtondivideActionPerformed(evt); 

            } 

        }); 

 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); 

        getContentPane().setLayout(layout); 

        layout.setHorizontalGroup( 

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

            .addGroup(layout.createSequentialGroup() 

                .addGap(18, 18, 18) 

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false) 

                    .addComponent(jTextFielddisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addGroup(layout.createSequentialGroup() 

                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                        .addComponent(jButtonaclear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                        .addComponent(jButtonequal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                        .addComponent(jButtondivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) 

                    .addGroup(layout.createSequentialGroup() 

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

                            .addGroup(layout.createSequentialGroup() 

                                .addGap(4, 4, 4) 

                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                            .addGroup(layout.createSequentialGroup() 

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))) 

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false) 

                            .addGroup(layout.createSequentialGroup() 

                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                                .addComponent(jButtonminus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                            .addGroup(layout.createSequentialGroup() 

                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                                .addComponent(jButtonmultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) 

                            .addGroup(layout.createSequentialGroup() 

                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                                .addComponent(jButtonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))) 

                .addContainerGap(18, Short.MAX_VALUE)) 

        ); 

        layout.setVerticalGroup( 

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) 

            .addGroup(layout.createSequentialGroup() 

                .addGap(18, 18, 18) 

                .addComponent(jTextFielddisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE) 

                .addGap(26, 26, 26) 

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 

                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 

                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtonminus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 

                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtonmultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED) 

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) 

                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtonaclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtonequal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE) 

                    .addComponent(jButtondivide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)) 

                .addGap(36, 36, 36)) 

        ); 

 

        pack(); 

    }// </editor-fold>//GEN-END:initComponents 

 

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("1");  

        else 

            jTextFielddisplay.setText(s+"1"); 

    }//GEN-LAST:event_jButton1ActionPerformed 

 

    private void jButtondivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondivideActionPerformed 

          num1=Double.parseDouble(jTextFielddisplay.getText() ); 

        jTextFielddisplay.setText(""); 

        operator="/"; 

    }//GEN-LAST:event_jButtondivideActionPerformed 

 

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("2");  

        else 

            jTextFielddisplay.setText(s+"2"); 

    }//GEN-LAST:event_jButton2ActionPerformed 

 

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("3");  

        else 

            jTextFielddisplay.setText(s+"3"); 

    }//GEN-LAST:event_jButton3ActionPerformed 

 

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed 

        String s=jTextFielddisplay.getText();  

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("4");  

        else 

            jTextFielddisplay.setText(s+"4"); 

    }//GEN-LAST:event_jButton4ActionPerformed 

 

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("5");  

        else 

            jTextFielddisplay.setText(s+"5"); 

    }//GEN-LAST:event_jButton5ActionPerformed 

 

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("6");  

        else 

            jTextFielddisplay.setText(s+"6"); 

    }//GEN-LAST:event_jButton6ActionPerformed 

 

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("7");  

        else 

            jTextFielddisplay.setText(s+"7"); 

    }//GEN-LAST:event_jButton7ActionPerformed 

 

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed 

        String s=jTextFielddisplay.getText();  

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("8");  

        else 

            jTextFielddisplay.setText(s+"8"); 

    }//GEN-LAST:event_jButton8ActionPerformed 

 

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed 

        String s=jTextFielddisplay.getText(); 

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("9");  

        else 

            jTextFielddisplay.setText(s+"9"); 

    }//GEN-LAST:event_jButton9ActionPerformed 

 

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed 

        String s=jTextFielddisplay.getText();  

        if(s.startsWith("0")) 

          jTextFielddisplay.setText("0");  

        else 

            jTextFielddisplay.setText(s+"0"); 

        jTextFielddisplay.setText(s+"0"); 

    }//GEN-LAST:event_jButton0ActionPerformed 

 

    private void jButtonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonplusActionPerformed 

        num1=Double.parseDouble(jTextFielddisplay.getText() ); 

        jTextFielddisplay.setText(""); 

        operator="+"; 

    }//GEN-LAST:event_jButtonplusActionPerformed 

 

    private void jButtonminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonminusActionPerformed 

        num1=Double.parseDouble(jTextFielddisplay.getText() ); 

        jTextFielddisplay.setText(""); 

        operator="-";   

    }//GEN-LAST:event_jButtonminusActionPerformed 

 

    private void jButtonmultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmultipleActionPerformed 

          num1=Double.parseDouble(jTextFielddisplay.getText() ); 

        jTextFielddisplay.setText(""); 

        operator="*"; 

    }//GEN-LAST:event_jButtonmultipleActionPerformed 

 

    private void jButtonequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonequalActionPerformed 

        num2=Double.parseDouble(jTextFielddisplay.getText() ); 

        switch(operator) 

        { 

            case"+": 

                res=num1+num2; 

                ans=String.format("%.0f",res  ); 

                jTextFielddisplay.setText(ans); 

                break; 

                 

            case"-": 

                res=num1-num2; 

                ans=String.format("%.0f",res  ); 

                jTextFielddisplay.setText(ans); 

                break; 

                 

            case"*": 

                res=num1*num2; 

                ans=String.format("%.0f",res  ); 

                jTextFielddisplay.setText(ans); 

                break; 

            case"/": 

                res=num1/num2; 

                ans=String.format("%.0f",res  ); 

                jTextFielddisplay.setText(ans); 

                break; 

        } 

    }//GEN-LAST:event_jButtonequalActionPerformed 

 

    private void jButtonaclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaclearActionPerformed 

       jTextFielddisplay.setText("");  

    }//GEN-LAST:event_jButtonaclearActionPerformed 

 

    /** 

     * @param args the command line arguments 

     */ 

    public static void main(String args[]) { 

        /* Set the Nimbus look and feel */ 

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) "> 

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. 

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html  

         */ 

        try { 

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { 

                if ("Nimbus".equals(info.getName())) { 

                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); 

                    break; 

                } 

            } 

        } catch (ClassNotFoundException ex) { 

            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

        } catch (InstantiationException ex) { 

            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

        } catch (IllegalAccessException ex) { 

            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 

            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 

        } 

        //</editor-fold> 

 

        /* Create and display the form */ 

        java.awt.EventQueue.invokeLater(new Runnable() { 

            public void run() { 

                new CalculatorJFrame().setVisible(true); 

            } 

        }); 

    } 

 

    // Variables declaration - do not modify//GEN-BEGIN:variables 

    private javax.swing.JButton jButton0; 

    private javax.swing.JButton jButton1; 

    private javax.swing.JButton jButton2; 

    private javax.swing.JButton jButton3; 

    private javax.swing.JButton jButton4; 

    private javax.swing.JButton jButton5; 

    private javax.swing.JButton jButton6; 

    private javax.swing.JButton jButton7; 

    private javax.swing.JButton jButton8; 

    private javax.swing.JButton jButton9; 

    private javax.swing.JButton jButtonaclear; 

    private javax.swing.JButton jButtondivide; 

    private javax.swing.JButton jButtonequal; 

    private javax.swing.JButton jButtonminus; 

    private javax.swing.JButton jButtonmultiple; 

    private javax.swing.JButton jButtonplus; 

    private javax.swing.JTextField jTextFielddisplay; 

    // End of variables declaration//GEN-END:variables 

} 
